### ISSUE TITLE
Label the tagging order of Tag chips in EXE6/BN6

### ISSUE THREAD

**Issue by ssbmars** [tangobattle/tango#191]
Sharing a feature request that I received:  
It would be helpful if the order of “tag chips” could be displayed as “TAG1” and “TAG2” in EXE6 and BN6.  
![image (3)](https://github.com/user-attachments/assets/d68aa43e-9894-4534-b522-39c2a3417171)

**Comment by ssbmars** [comment]
Probably requires some memory inspection to find out how the order is saved. I don't expect this to already be recorded by Tango.

**Comment by ArthurCose** [comment]
Implemented in efed74739620289a4c467a713a2d0cae51b64a3e
