### ISSUE TITLE
Tango not using updated save files in some cases

### ISSUE THREAD

**Issue by ssbmars** [tangobattle/tango#192]
To reproduce this bug, select an existing save, modify the build (make an obvious edit to the navicust) and then save in-game, then close the game without closing Tango. At this point, the save preview will show that the save has been updated. Select a different save from the dropdown, then re-select the first save. The save preview will now revert to the old version of the save file.  

From here, I launched the game in singleplayer and it loaded the updated save, despite showing the not updated save. Then I closed out of singleplayer and opened another Tango instance and started a pvp match between my local instances (using a different save for the 2nd instance). During the pvp match, it used the old save file. I ended the match without closing either instance, then started a new match. This time, it used the updated save file.  

I tested this with BN6 by switching out airshoes (old save) with floatshoes (new save) and testing the interaction with the cracked/broken panels created by dustcross.

**Comment by ArthurCose** [comment]
Conversation continued through discord, appears to be fixed by a2f95fa2bd4062c267cf39602e849163dfa83b5a
