### ISSUE TITLE
Remember last save file

### ISSUE THREAD

**Issue by ssbmars** [tangobattle/tango#8]
When opening Tango, automatically select and display the save file, associated game, and patch that was being used the last time Tango was closed. This may be best as an option that can be toggled on and off in settings.

**Comment by Lumanator** [comment]
On top of that, I would also like to suggest "per-save" settings, for if the patches drastically changes the meta so much, you assign it to one of your save files. Timaeus patch messed with the meta so much that I felt like the best thing would be to create a separate save file just for that specific patch.
